/*
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/libpod/images/json' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.alersrt.pod4j.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.github.alersrt.pod4j.openapi.model.DriverData;
import io.github.alersrt.pod4j.openapi.model.InspectContainerConfig;
import io.github.alersrt.pod4j.openapi.model.InspectContainerHostConfig;
import io.github.alersrt.pod4j.openapi.model.InspectContainerState;
import io.github.alersrt.pod4j.openapi.model.InspectMount;
import io.github.alersrt.pod4j.openapi.model.InspectNetworkSettings;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InspectContainerData
 */
class InspectContainerDataTest {
    private final InspectContainerData model = new InspectContainerData();

    /**
     * Model tests for InspectContainerData
     */
    @Test
    void testInspectContainerData() {
        // TODO: test InspectContainerData
    }

    /**
     * Test the property 'appArmorProfile'
     */
    @Test
    void appArmorProfileTest() {
        // TODO: test appArmorProfile
    }

    /**
     * Test the property 'args'
     */
    @Test
    void argsTest() {
        // TODO: test args
    }

    /**
     * Test the property 'boundingCaps'
     */
    @Test
    void boundingCapsTest() {
        // TODO: test boundingCaps
    }

    /**
     * Test the property 'config'
     */
    @Test
    void configTest() {
        // TODO: test config
    }

    /**
     * Test the property 'conmonPidFile'
     */
    @Test
    void conmonPidFileTest() {
        // TODO: test conmonPidFile
    }

    /**
     * Test the property 'created'
     */
    @Test
    void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'dependencies'
     */
    @Test
    void dependenciesTest() {
        // TODO: test dependencies
    }

    /**
     * Test the property 'driver'
     */
    @Test
    void driverTest() {
        // TODO: test driver
    }

    /**
     * Test the property 'effectiveCaps'
     */
    @Test
    void effectiveCapsTest() {
        // TODO: test effectiveCaps
    }

    /**
     * Test the property 'execIDs'
     */
    @Test
    void execIDsTest() {
        // TODO: test execIDs
    }

    /**
     * Test the property 'graphDriver'
     */
    @Test
    void graphDriverTest() {
        // TODO: test graphDriver
    }

    /**
     * Test the property 'hostConfig'
     */
    @Test
    void hostConfigTest() {
        // TODO: test hostConfig
    }

    /**
     * Test the property 'hostnamePath'
     */
    @Test
    void hostnamePathTest() {
        // TODO: test hostnamePath
    }

    /**
     * Test the property 'hostsPath'
     */
    @Test
    void hostsPathTest() {
        // TODO: test hostsPath
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'image'
     */
    @Test
    void imageTest() {
        // TODO: test image
    }

    /**
     * Test the property 'imageDigest'
     */
    @Test
    void imageDigestTest() {
        // TODO: test imageDigest
    }

    /**
     * Test the property 'imageName'
     */
    @Test
    void imageNameTest() {
        // TODO: test imageName
    }

    /**
     * Test the property 'isInfra'
     */
    @Test
    void isInfraTest() {
        // TODO: test isInfra
    }

    /**
     * Test the property 'isService'
     */
    @Test
    void isServiceTest() {
        // TODO: test isService
    }

    /**
     * Test the property 'kubeExitCodePropagation'
     */
    @Test
    void kubeExitCodePropagationTest() {
        // TODO: test kubeExitCodePropagation
    }

    /**
     * Test the property 'mountLabel'
     */
    @Test
    void mountLabelTest() {
        // TODO: test mountLabel
    }

    /**
     * Test the property 'mounts'
     */
    @Test
    void mountsTest() {
        // TODO: test mounts
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'networkSettings'
     */
    @Test
    void networkSettingsTest() {
        // TODO: test networkSettings
    }

    /**
     * Test the property 'ocIConfigPath'
     */
    @Test
    void ocIConfigPathTest() {
        // TODO: test ocIConfigPath
    }

    /**
     * Test the property 'ocIRuntime'
     */
    @Test
    void ocIRuntimeTest() {
        // TODO: test ocIRuntime
    }

    /**
     * Test the property 'path'
     */
    @Test
    void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'pidFile'
     */
    @Test
    void pidFileTest() {
        // TODO: test pidFile
    }

    /**
     * Test the property 'pod'
     */
    @Test
    void podTest() {
        // TODO: test pod
    }

    /**
     * Test the property 'processLabel'
     */
    @Test
    void processLabelTest() {
        // TODO: test processLabel
    }

    /**
     * Test the property 'resolvConfPath'
     */
    @Test
    void resolvConfPathTest() {
        // TODO: test resolvConfPath
    }

    /**
     * Test the property 'restartCount'
     */
    @Test
    void restartCountTest() {
        // TODO: test restartCount
    }

    /**
     * Test the property 'rootfs'
     */
    @Test
    void rootfsTest() {
        // TODO: test rootfs
    }

    /**
     * Test the property 'sizeRootFs'
     */
    @Test
    void sizeRootFsTest() {
        // TODO: test sizeRootFs
    }

    /**
     * Test the property 'sizeRw'
     */
    @Test
    void sizeRwTest() {
        // TODO: test sizeRw
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'staticDir'
     */
    @Test
    void staticDirTest() {
        // TODO: test staticDir
    }

    /**
     * Test the property 'lockNumber'
     */
    @Test
    void lockNumberTest() {
        // TODO: test lockNumber
    }

}
