/*
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/libpod/images/json' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.alersrt.pod4j.openapi.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;


import io.github.alersrt.pod4j.openapi.ApiClient;
/**
 * TypeMount contains options for using a volume as a Mount-type volume.
 */
@JsonPropertyOrder({
  TypeMount.JSON_PROPERTY_FS_TYPE,
  TypeMount.JSON_PROPERTY_MOUNT_FLAGS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-28T20:49:08.759389952+07:00[Asia/Barnaul]", comments = "Generator version: 7.7.0")
public class TypeMount {
  public static final String JSON_PROPERTY_FS_TYPE = "FsType";
  private String fsType;

  public static final String JSON_PROPERTY_MOUNT_FLAGS = "MountFlags";
  private List<String> mountFlags = new ArrayList<>();

  public TypeMount() { 
  }

  public TypeMount fsType(String fsType) {
    this.fsType = fsType;
    return this;
  }

  /**
   * FsType specifies the filesystem type for the mount volume. Optional.
   * @return fsType
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_FS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFsType() {
    return fsType;
  }


  @JsonProperty(JSON_PROPERTY_FS_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFsType(String fsType) {
    this.fsType = fsType;
  }


  public TypeMount mountFlags(List<String> mountFlags) {
    this.mountFlags = mountFlags;
    return this;
  }

  public TypeMount addMountFlagsItem(String mountFlagsItem) {
    if (this.mountFlags == null) {
      this.mountFlags = new ArrayList<>();
    }
    this.mountFlags.add(mountFlagsItem);
    return this;
  }

  /**
   * MountFlags defines flags to pass when mounting the volume. Optional.
   * @return mountFlags
   */
  @jakarta.annotation.Nullable

  @JsonProperty(JSON_PROPERTY_MOUNT_FLAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getMountFlags() {
    return mountFlags;
  }


  @JsonProperty(JSON_PROPERTY_MOUNT_FLAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMountFlags(List<String> mountFlags) {
    this.mountFlags = mountFlags;
  }


  /**
   * Return true if this TypeMount object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TypeMount typeMount = (TypeMount) o;
    return Objects.equals(this.fsType, typeMount.fsType) &&
        Objects.equals(this.mountFlags, typeMount.mountFlags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fsType, mountFlags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TypeMount {\n");
    sb.append("    fsType: ").append(toIndentedString(fsType)).append("\n");
    sb.append("    mountFlags: ").append(toIndentedString(mountFlags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `FsType` to the URL query string
    if (getFsType() != null) {
      joiner.add(String.format("%sFsType%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFsType()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `MountFlags` to the URL query string
    if (getMountFlags() != null) {
      for (int i = 0; i < getMountFlags().size(); i++) {
        joiner.add(String.format("%sMountFlags%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            URLEncoder.encode(ApiClient.valueToString(getMountFlags().get(i)), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
      }
    }

    return joiner.toString();
  }
}

