/*
 * supports a RESTful API for the Libpod library
 * This documentation describes the Podman v2.x+ RESTful API. It consists of a Docker-compatible API and a Libpod API providing support for Podman’s unique features such as pods.  To start the service and keep it running for 5,000 seconds (-t 0 runs forever):  podman system service -t 5000 &  You can then use cURL on the socket using requests documented below.  NOTE: if you install the package podman-docker, it will create a symbolic link for /run/docker.sock to /run/podman/podman.sock  NOTE: Some fields in the API response JSON are encoded as omitempty, which means that if said field has a zero value, they will not be encoded in the API response. This is a feature to help reduce the size of the JSON responses returned via the API.  NOTE: Due to the limitations of [go-swagger](https://github.com/go-swagger/go-swagger), some field values that have a complex type show up as null in the docs as well as in the API responses. This is because the zero value for the field type is null. The field description in the docs will state what type the field is expected to be for such cases.  See podman-system-service(1) for more information.  Quick Examples:  'podman info'  curl --unix-socket /run/podman/podman.sock http://d/v5.0.0/libpod/info  'podman pull quay.io/containers/podman'  curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/images/create?fromImage=quay.io%2Fcontainers%2Fpodman'  'podman list images'  curl --unix-socket /run/podman/podman.sock -v 'http://d/v5.0.0/libpod/images/json' | jq
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: podman@lists.podman.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.alersrt.pod4j.openapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.alersrt.pod4j.openapi.JSON;

import java.io.IOException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * VolumeCreateOptions
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-11-29T01:29:49.168634544+07:00[Asia/Barnaul]", comments = "Generator version: 7.7.0")
public class VolumeCreateOptions {
    public static final String SERIALIZED_NAME_DRIVER = "Driver";
    public static final String SERIALIZED_NAME_IGNORE_IF_EXISTS = "IgnoreIfExists";
    public static final String SERIALIZED_NAME_LABEL = "Label";
    public static final String SERIALIZED_NAME_LABELS = "Labels";
    public static final String SERIALIZED_NAME_NAME = "Name";
    public static final String SERIALIZED_NAME_OPTIONS = "Options";
    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("Driver");
        openapiFields.add("IgnoreIfExists");
        openapiFields.add("Label");
        openapiFields.add("Labels");
        openapiFields.add("Name");
        openapiFields.add("Options");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    @SerializedName(SERIALIZED_NAME_DRIVER)
    private String driver;
    @SerializedName(SERIALIZED_NAME_IGNORE_IF_EXISTS)
    private Boolean ignoreIfExists;
    @SerializedName(SERIALIZED_NAME_LABEL)
    private Map<String, String> label = new HashMap<>();
    @SerializedName(SERIALIZED_NAME_LABELS)
    private Map<String, String> labels = new HashMap<>();
    @SerializedName(SERIALIZED_NAME_NAME)
    private String name;
    @SerializedName(SERIALIZED_NAME_OPTIONS)
    private Map<String, String> options = new HashMap<>();

    public VolumeCreateOptions() {
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to VolumeCreateOptions
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!VolumeCreateOptions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in VolumeCreateOptions is not found in the empty JSON string", VolumeCreateOptions.openapiRequiredFields));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!VolumeCreateOptions.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VolumeCreateOptions` properties. JSON: %s", entry.getKey(), jsonElement));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if ((jsonObj.get("Driver") != null && !jsonObj.get("Driver").isJsonNull()) && !jsonObj.get("Driver").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `Driver` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Driver").toString()));
        }
        if ((jsonObj.get("Name") != null && !jsonObj.get("Name").isJsonNull()) && !jsonObj.get("Name").isJsonPrimitive()) {
            throw new IllegalArgumentException(String.format("Expected the field `Name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Name").toString()));
        }
    }

    /**
     * Create an instance of VolumeCreateOptions given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of VolumeCreateOptions
     * @throws IOException if the JSON string is invalid with respect to VolumeCreateOptions
     */
    public static VolumeCreateOptions fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, VolumeCreateOptions.class);
    }

    public VolumeCreateOptions driver(String driver) {
        this.driver = driver;
        return this;
    }

    /**
     * Volume driver to use
     *
     * @return driver
     */
    @jakarta.annotation.Nullable

    public String getDriver() {
        return driver;
    }

    public void setDriver(String driver) {
        this.driver = driver;
    }

    public VolumeCreateOptions ignoreIfExists(Boolean ignoreIfExists) {
        this.ignoreIfExists = ignoreIfExists;
        return this;
    }

    /**
     * Ignore existing volumes
     *
     * @return ignoreIfExists
     */
    @jakarta.annotation.Nullable

    public Boolean getIgnoreIfExists() {
        return ignoreIfExists;
    }

    public void setIgnoreIfExists(Boolean ignoreIfExists) {
        this.ignoreIfExists = ignoreIfExists;
    }

    public VolumeCreateOptions label(Map<String, String> label) {
        this.label = label;
        return this;
    }

    public VolumeCreateOptions putLabelItem(String key, String labelItem) {
        if (this.label == null) {
            this.label = new HashMap<>();
        }
        this.label.put(key, labelItem);
        return this;
    }

    /**
     * User-defined key/value metadata. Provided for compatibility
     *
     * @return label
     */
    @jakarta.annotation.Nullable

    public Map<String, String> getLabel() {
        return label;
    }

    public void setLabel(Map<String, String> label) {
        this.label = label;
    }

    public VolumeCreateOptions labels(Map<String, String> labels) {
        this.labels = labels;
        return this;
    }

    public VolumeCreateOptions putLabelsItem(String key, String labelsItem) {
        if (this.labels == null) {
            this.labels = new HashMap<>();
        }
        this.labels.put(key, labelsItem);
        return this;
    }

    /**
     * User-defined key/value metadata. Preferred field, will override Label
     *
     * @return labels
     */
    @jakarta.annotation.Nullable

    public Map<String, String> getLabels() {
        return labels;
    }

    public void setLabels(Map<String, String> labels) {
        this.labels = labels;
    }

    public VolumeCreateOptions name(String name) {
        this.name = name;
        return this;
    }

    /**
     * New volume&#39;s name. Can be left blank
     *
     * @return name
     */
    @jakarta.annotation.Nullable

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public VolumeCreateOptions options(Map<String, String> options) {
        this.options = options;
        return this;
    }

    public VolumeCreateOptions putOptionsItem(String key, String optionsItem) {
        if (this.options == null) {
            this.options = new HashMap<>();
        }
        this.options.put(key, optionsItem);
        return this;
    }

    /**
     * Mapping of driver options and values.
     *
     * @return options
     */
    @jakarta.annotation.Nullable

    public Map<String, String> getOptions() {
        return options;
    }

    public void setOptions(Map<String, String> options) {
        this.options = options;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VolumeCreateOptions volumeCreateOptions = (VolumeCreateOptions) o;
        return Objects.equals(this.driver, volumeCreateOptions.driver) &&
                Objects.equals(this.ignoreIfExists, volumeCreateOptions.ignoreIfExists) &&
                Objects.equals(this.label, volumeCreateOptions.label) &&
                Objects.equals(this.labels, volumeCreateOptions.labels) &&
                Objects.equals(this.name, volumeCreateOptions.name) &&
                Objects.equals(this.options, volumeCreateOptions.options);
    }

    @Override
    public int hashCode() {
        return Objects.hash(driver, ignoreIfExists, label, labels, name, options);
    }

    @Override
    public String toString() {
        String sb = "class VolumeCreateOptions {\n" +
                "    driver: " + toIndentedString(driver) + "\n" +
                "    ignoreIfExists: " + toIndentedString(ignoreIfExists) + "\n" +
                "    label: " + toIndentedString(label) + "\n" +
                "    labels: " + toIndentedString(labels) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    options: " + toIndentedString(options) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Convert an instance of VolumeCreateOptions to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!VolumeCreateOptions.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'VolumeCreateOptions' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<VolumeCreateOptions> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(VolumeCreateOptions.class));

            return (TypeAdapter<T>) new TypeAdapter<VolumeCreateOptions>() {
                @Override
                public void write(JsonWriter out, VolumeCreateOptions value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public VolumeCreateOptions read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }
}

